/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FuturePlanningService } from "../futurePlanning.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FuturePlanningCreateInput } from "./FuturePlanningCreateInput";
import { FuturePlanning } from "./FuturePlanning";
import { FuturePlanningFindManyArgs } from "./FuturePlanningFindManyArgs";
import { FuturePlanningWhereUniqueInput } from "./FuturePlanningWhereUniqueInput";
import { FuturePlanningUpdateInput } from "./FuturePlanningUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FuturePlanningControllerBase {
  constructor(
    protected readonly service: FuturePlanningService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FuturePlanning })
  @nestAccessControl.UseRoles({
    resource: "FuturePlanning",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFuturePlanning(
    @common.Body() data: FuturePlanningCreateInput
  ): Promise<FuturePlanning> {
    return await this.service.createFuturePlanning({
      data: data,
      select: {
        createdAt: true,
        description: true,
        dueDate: true,
        feature: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FuturePlanning] })
  @ApiNestedQuery(FuturePlanningFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FuturePlanning",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async futurePlannings(
    @common.Req() request: Request
  ): Promise<FuturePlanning[]> {
    const args = plainToClass(FuturePlanningFindManyArgs, request.query);
    return this.service.futurePlannings({
      ...args,
      select: {
        createdAt: true,
        description: true,
        dueDate: true,
        feature: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FuturePlanning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FuturePlanning",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async futurePlanning(
    @common.Param() params: FuturePlanningWhereUniqueInput
  ): Promise<FuturePlanning | null> {
    const result = await this.service.futurePlanning({
      where: params,
      select: {
        createdAt: true,
        description: true,
        dueDate: true,
        feature: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FuturePlanning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FuturePlanning",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFuturePlanning(
    @common.Param() params: FuturePlanningWhereUniqueInput,
    @common.Body() data: FuturePlanningUpdateInput
  ): Promise<FuturePlanning | null> {
    try {
      return await this.service.updateFuturePlanning({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          dueDate: true,
          feature: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FuturePlanning })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FuturePlanning",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFuturePlanning(
    @common.Param() params: FuturePlanningWhereUniqueInput
  ): Promise<FuturePlanning | null> {
    try {
      return await this.service.deleteFuturePlanning({
        where: params,
        select: {
          createdAt: true,
          description: true,
          dueDate: true,
          feature: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
