/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IntegrationTestService } from "../integrationTest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IntegrationTestCreateInput } from "./IntegrationTestCreateInput";
import { IntegrationTest } from "./IntegrationTest";
import { IntegrationTestFindManyArgs } from "./IntegrationTestFindManyArgs";
import { IntegrationTestWhereUniqueInput } from "./IntegrationTestWhereUniqueInput";
import { IntegrationTestUpdateInput } from "./IntegrationTestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IntegrationTestControllerBase {
  constructor(
    protected readonly service: IntegrationTestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IntegrationTest })
  @nestAccessControl.UseRoles({
    resource: "IntegrationTest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createIntegrationTest(
    @common.Body() data: IntegrationTestCreateInput
  ): Promise<IntegrationTest> {
    return await this.service.createIntegrationTest({
      data: data,
      select: {
        component: true,
        createdAt: true,
        id: true,
        result: true,
        testedAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IntegrationTest] })
  @ApiNestedQuery(IntegrationTestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IntegrationTest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async integrationTests(
    @common.Req() request: Request
  ): Promise<IntegrationTest[]> {
    const args = plainToClass(IntegrationTestFindManyArgs, request.query);
    return this.service.integrationTests({
      ...args,
      select: {
        component: true,
        createdAt: true,
        id: true,
        result: true,
        testedAt: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IntegrationTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IntegrationTest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async integrationTest(
    @common.Param() params: IntegrationTestWhereUniqueInput
  ): Promise<IntegrationTest | null> {
    const result = await this.service.integrationTest({
      where: params,
      select: {
        component: true,
        createdAt: true,
        id: true,
        result: true,
        testedAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IntegrationTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IntegrationTest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateIntegrationTest(
    @common.Param() params: IntegrationTestWhereUniqueInput,
    @common.Body() data: IntegrationTestUpdateInput
  ): Promise<IntegrationTest | null> {
    try {
      return await this.service.updateIntegrationTest({
        where: params,
        data: data,
        select: {
          component: true,
          createdAt: true,
          id: true,
          result: true,
          testedAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IntegrationTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IntegrationTest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteIntegrationTest(
    @common.Param() params: IntegrationTestWhereUniqueInput
  ): Promise<IntegrationTest | null> {
    try {
      return await this.service.deleteIntegrationTest({
        where: params,
        select: {
          component: true,
          createdAt: true,
          id: true,
          result: true,
          testedAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
