/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BlockchainService } from "../blockchain.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BlockchainCreateInput } from "./BlockchainCreateInput";
import { Blockchain } from "./Blockchain";
import { BlockchainFindManyArgs } from "./BlockchainFindManyArgs";
import { BlockchainWhereUniqueInput } from "./BlockchainWhereUniqueInput";
import { BlockchainUpdateInput } from "./BlockchainUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BlockchainControllerBase {
  constructor(
    protected readonly service: BlockchainService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Blockchain })
  @nestAccessControl.UseRoles({
    resource: "Blockchain",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBlockchain(
    @common.Body() data: BlockchainCreateInput
  ): Promise<Blockchain> {
    return await this.service.createBlockchain({
      data: data,
      select: {
        blockData: true,
        createdAt: true,
        hash: true,
        id: true,
        previousHash: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Blockchain] })
  @ApiNestedQuery(BlockchainFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Blockchain",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async blockchains(@common.Req() request: Request): Promise<Blockchain[]> {
    const args = plainToClass(BlockchainFindManyArgs, request.query);
    return this.service.blockchains({
      ...args,
      select: {
        blockData: true,
        createdAt: true,
        hash: true,
        id: true,
        previousHash: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Blockchain })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Blockchain",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async blockchain(
    @common.Param() params: BlockchainWhereUniqueInput
  ): Promise<Blockchain | null> {
    const result = await this.service.blockchain({
      where: params,
      select: {
        blockData: true,
        createdAt: true,
        hash: true,
        id: true,
        previousHash: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Blockchain })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Blockchain",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBlockchain(
    @common.Param() params: BlockchainWhereUniqueInput,
    @common.Body() data: BlockchainUpdateInput
  ): Promise<Blockchain | null> {
    try {
      return await this.service.updateBlockchain({
        where: params,
        data: data,
        select: {
          blockData: true,
          createdAt: true,
          hash: true,
          id: true,
          previousHash: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Blockchain })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Blockchain",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBlockchain(
    @common.Param() params: BlockchainWhereUniqueInput
  ): Promise<Blockchain | null> {
    try {
      return await this.service.deleteBlockchain({
        where: params,
        select: {
          blockData: true,
          createdAt: true,
          hash: true,
          id: true,
          previousHash: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
